---
- name: delete the server
  uri:
    url: "{{leo_url}}/v2/iaas/virtual-machines/{{cloned_vm.json.data.id}}"
    method: DELETE
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 204
    timeout: 300

- name: Wait for config apply
  wait_for:
    timeout: 10
  delegate_to: localhost

- debug:
    msg: "Ping test is successful for {{template_id}}, node has been deleted ..."
