---
- name: Find netgateways server in related datacenter node
  uri:
    url: "{{leo_url}}/v2/repo/images/{{template_id}}"
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: image
  delegate_to: localhost

- name: debug_lower
  debug:
    var: image.json.data.name | lower

- name: set_factttt
  set_fact:
    image_name: "{{ image.json.data.name | lower }}"

- name: image_name
  debug:
    var: image_name

- name: debug cloned_vm.uuid
  debug:
    var: cloned_vm.json.data.uuid

- set_fact:
    uuid: "{{ cloned_vm.json.data.uuid }}"

- name: debug uuid
  debug:
    var: uuid

- name: Use Public API to Export VM
  uri:
    url: "{{ api_url }}/v2/iaas/virtual-machines/{{ cloned_vm.json.data.id }}/export"
    method: POST
    headers:
      Authorization: "Bearer {{ user_token }}"
      Content-Type: "application/x-www-form-urlencoded"
    body: "name={{ image_name }}&repo_server_id={{ repo_server_id }}&cpu_type={{ cpu_type }}"
    body_format: form-urlencoded
    status_code: 200, 201, 204
  register: api_result
  ignore_errors: yes

- name: Debug API Result
  debug:
    var: api_result
