---
- name: wait for config apply
  wait_for:
    timeout: 10

- name: shutdown the server
  uri:
    url: "{{leo_url}}/v2/iaas/virtual-machines/{{cloned_vm.json.data.id}}/shutdown"
    method: PUT
    headers:
      Authorization: "Bearer {{ user_token }}"
    body: "force=1"
    return_content: yes
    status_code: 204
    timeout: 300

- name: Wait until the template is halted
  uri:
    url: "{{leo_url}}/v2/iaas/virtual-machines/{{ cloned_vm.json.data.id }}/status"
    method: GET
    headers:
      Authorization: "Bearer {{ user_token }}"
    return_content: yes
    status_code: 200
    timeout: 300
  register: cloned_vm_status
  until: cloned_vm_status.json.data.status == "halted"
  retries: 100
  delay: 4
  ignore_errors: yes